import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import '@radix-ui/themes/styles.css';
import { Theme, ThemePanel } from '@radix-ui/themes';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Theme accentColor="grass" grayColor="sand" radius="large" scaling="95%">
              <Navbar/>
        {children}
     
        </Theme>
        </body>
    </html>
  );
}
