import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

import "../../static/js/resources/OwlCarousel2-2.3.4/dist/assets/owl.carousel.css";
import "../../static/js/resources/OwlCarousel2-2.3.4/dist/assets/owl.theme.default.css";
import "../../static/css/owlCarousel.css";

import Script from "next/script";
import Chat from "@/components/Chat";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme
          appearance=""
          accentColor="grass"
          grayColor="sand"
          radius="large"
          scaling="95%"
        >
          <Navbar />
          <div className="grid grid-cols-7 justify-between gap-2 text-white">
            <div className="col-span-1 z-40 lg:block">
              <Sidebar />
            </div>

            <div className="col-span-7 ml-10 md:ml-12 lg:ml-0 lg:col-span-6 xl:col-span-4 px-2">
              {children}
            </div>

            <div className="col-span-2 hidden xl:grid justify-items-end">
              <Chat />
            </div>
          </div>
        </Theme>
        <Script src="../../static/js/resources/jquery.js"></Script>
        <Script src="../../static/js/owlCarousel.js"></Script>
        <Script src="../../static/js/resources/OwlCarousel2-2.3.4/dist/owl.carousel.js"></Script>
        <Script src="../../static/js/sidebar.js"></Script>
      </body>
    </html>
  );
}
